version: 2

rubygems-login: &rubygems-login
  run:
    name: Login to RubyGems
    command: |
      mkdir ~/.gem
      echo ":rubygems_api_key: $RUBYGEMS_API_KEY" >  ~/.gem/credentials
      chmod 0600 ~/.gem/credentials

install-git: &install-git
  run: apk add --no-cache --no-progress git

defaults: &defaults
  steps:
    - *install-git
    - checkout
    - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
    - run: bundle exec rake test
  working_directory: ~/sshkit-backends-netssh_global

default-deploys: &default-deploys
  docker:
    - image: ruby:alpine
  working_directory: ~/sshkit-backends-netssh_global

jobs:
  deploy-gem:
    <<: *default-deploys
    steps:
      - *install-git
      - checkout
      - *rubygems-login
      - run:
          name: Build gem
          command: gem build "$CIRCLE_PROJECT_REPONAME".gemspec
      - run:
          name: Publish gem to RubyGems
          command: |
            package=$(ls -t1 "$CIRCLE_PROJECT_REPONAME"*.gem | head -1)
            gem push "$CIRCLE_PROJECT_REPONAME"-"$(echo $CIRCLE_TAG | sed -e 's/v//')".gem
  deploy-pre-release-gem:
    <<: *default-deploys
    steps:
      - *install-git
      - checkout
      - *rubygems-login
      - run:
          name: Install gem-versioner
          command: gem install gem-versioner
      - run:
          name: Build gem
          command: PRE_RELEASE="$CIRCLE_BRANCH" gem build "$CIRCLE_PROJECT_REPONAME".gemspec
      - run:
          name: Push pre-release gem to RubyGems
          command: |
            package=$(ls -t1 "$CIRCLE_PROJECT_REPONAME"*.gem | head -1)
            gem push "$package"
  test-ruby-2.2:
    <<: *defaults
    docker:
      - image: ruby:2.2-alpine
  test-ruby-2.3:
    <<: *defaults
    docker:
      - image: ruby:2.3-alpine
  test-ruby-2.4:
    <<: *defaults
    docker:
      - image: ruby:2.4-alpine
  test-ruby-2.5:
    <<: *defaults
    docker:
      - image: ruby:2.5-alpine

workflows:
  version: 2
  test-then-release-gem:
    jobs:
      - test-ruby-2.2:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d\+/
      - test-ruby-2.3:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d\+/
      - test-ruby-2.4:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d\+/
      - test-ruby-2.5:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d\+/
      - deploy-gem:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d\+/
          requires:
            - test-ruby-2.2
            - test-ruby-2.3
            - test-ruby-2.4
            - test-ruby-2.5
      - deploy-pre-release-gem:
          context: org-global
          filters:
            branches:
              ignore: master
          requires:
            - test-ruby-2.2
            - test-ruby-2.3
            - test-ruby-2.4
            - test-ruby-2.5
