version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.4
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
